language: python
python:

  - "3.5"
  - "3.5-dev" # 3.5 development branch

env:
  - DJANGO_VERSION=1.10.4

# command to install dependencies  
install:
- pip install -r requirements.txt


# command to run tests
script:
- "python manage.py test"

notifications:
  email:
    recipients:
      - eduard.erja@gmail.com
    on_success: always
    on_failure: always
  slack:
    rooms:
      - edteamcerner:MBeDARMBGbbdENrkB5B2oipQ#healthy
