language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=1.10.4

# command to install dependencies  
install:
- pip install -r requirements.txt
- pip install -q Django==$DJANGO_VERSION
- python setup.py -q install

# command to run tests
script: "python manage.py test"

notifications:
  email:
    recipients:
      - eduard.erja@gmail.com
    on_success: always
    on_failure: always