# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0003_auto_20161208_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='ref_number',
            field=models.IntegerField(verbose_name='Reference Number'),
        ),
    ]
