# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthy', '0004_auto_20161208_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='ref_number',
            field=models.IntegerField(unique=True, verbose_name='Reference Number'),
        ),
    ]
